'use client';

import { useState, useTransition } from 'react';
import { createVariant, generateVariantIds } from '@/app/actions/variants';
import { useActionState } from 'react';
import { Download, Loader2, Plus, Printer, X } from 'lucide-react';
import { sanitizeCode } from '@/lib/verification-id';
import toast from 'react-hot-toast';

const COMMON_ATTRIBUTE_KEYS = ['Color', 'Size', 'Storage', 'Weight', 'Material', 'Style', 'Pattern'];

function downloadCsv(ids: string[]) {
  const rows = ['Unit #,Verification ID', ...ids.map((id, i) => `${i + 1},${id}`)];
  const blob = new Blob([rows.join('\n')], { type: 'text/csv' });
  const url  = URL.createObjectURL(blob);
  const a    = document.createElement('a');
  a.href     = url;
  a.download = 'verification-ids.csv';
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}

function printIds(ids: string[]) {
  const rows = ids.map((id, i) => `
    <tr>
      <td style="padding:6px 12px;border-bottom:1px solid #e5e7eb;font-family:monospace;font-size:11px">${i + 1}</td>
      <td style="padding:6px 12px;border-bottom:1px solid #e5e7eb;font-family:monospace;font-size:11px;font-weight:bold">${id}</td>
      <td style="padding:6px 12px;border-bottom:1px solid #e5e7eb"></td>
    </tr>`).join('');
  const html = `<!doctype html><html><head><title>Verification IDs</title></head><body>
    <h2 style="font-family:sans-serif;font-size:14px;margin-bottom:12px">Trusta Verification IDs (${ids.length} units)</h2>
    <table style="border-collapse:collapse;width:100%;font-family:sans-serif">
      <thead><tr style="background:#f9fafb">
        <th style="padding:8px 12px;text-align:left;font-size:10px;text-transform:uppercase;color:#6b7280;border-bottom:2px solid #e5e7eb">#</th>
        <th style="padding:8px 12px;text-align:left;font-size:10px;text-transform:uppercase;color:#6b7280;border-bottom:2px solid #e5e7eb">Verification ID</th>
        <th style="padding:8px 12px;text-align:left;font-size:10px;text-transform:uppercase;color:#6b7280;border-bottom:2px solid #e5e7eb">Applied To (unit label)</th>
      </tr></thead>
      <tbody>${rows}</tbody>
    </table>
    <p style="font-family:sans-serif;font-size:10px;color:#9ca3af;margin-top:16px">Generated by Trusta · trusta.in/verify</p>
    <script>window.onload=()=>window.print()</script>
  </body></html>`;
  const w = window.open('', '_blank');
  if (w) { w.document.write(html); w.document.close(); }
}

export default function VariantForm({ productId }: { productId: string }) {
  const createVariantForProduct = createVariant.bind(null, productId);
  const [state, action, pending] = useActionState(createVariantForProduct, undefined);

  const [variantCode, setVariantCode] = useState('');
  const [attrs, setAttrs] = useState<{ key: string; value: string }[]>([{ key: 'Color', value: '' }]);

  // Generate-IDs state
  const [genQty, setGenQty] = useState(1);
  const [genLoading, startGenTransition] = useTransition();
  const [generatedIds, setGeneratedIds] = useState<string[]>([]);
  const [genError, setGenError] = useState<string | null>(null);

  const addAttr    = () => setAttrs((a) => [...a, { key: '', value: '' }]);
  const removeAttr = (i: number) => setAttrs((a) => a.filter((_, idx) => idx !== i));
  const updateAttr = (i: number, field: 'key' | 'value', val: string) =>
    setAttrs((a) => a.map((at, idx) => (idx === i ? { ...at, [field]: val } : at)));

  const attributesJson = JSON.stringify(
    Object.fromEntries(attrs.filter((a) => a.key && a.value).map((a) => [a.key, a.value]))
  );

  const handleGenerateIds = () => {
    if (!state?.variantId) return;
    setGenError(null);
    startGenTransition(async () => {
      const res = await generateVariantIds(state.variantId!, genQty);
      if (res.success && res.ids) {
        setGeneratedIds(res.ids);
        toast.success(`${res.ids.length} verification IDs generated`);
      } else {
        setGenError(res.error ?? 'Generation failed');
      }
    });
  };

  const inputCls = 'w-full px-3.5 py-2.5 bg-white border border-gray-200 rounded-xl text-gray-900 text-sm placeholder-gray-400 focus:outline-none focus:ring-2 focus:ring-red-500/30 focus:border-red-400 transition';

  return (
    <div className="space-y-5">
      {/* ── Variant creation form ── */}
      <div className="bg-white border border-gray-200 rounded-2xl p-6 shadow-sm">
        <h3 className="text-gray-900 font-bold text-lg mb-5 flex items-center gap-2">
          <Plus className="w-5 h-5 text-red-600" />
          Add New Variant
        </h3>

        {state?.message && (
          <div className="mb-4 p-3 bg-red-50 border border-red-200 rounded-xl text-red-600 text-sm">
            {state.message}
          </div>
        )}
        {state?.success && (
          <div className="mb-4 p-3 bg-green-50 border border-green-200 rounded-xl text-green-600 text-sm">
            Variant created successfully!
          </div>
        )}

        <form action={action} className="space-y-5">
          <input type="hidden" name="attributes_raw" value={attributesJson} />

          <div>
            <label className="block text-sm font-medium text-gray-700 mb-3">Variant Attributes</label>
            <div className="space-y-2">
              {attrs.map((attr, i) => (
                <div key={i} className="flex gap-2">
                  <select
                    value={attr.key}
                    onChange={(e) => updateAttr(i, 'key', e.target.value)}
                    className="flex-1 px-3 py-2 bg-white border border-gray-200 rounded-lg text-gray-900 text-sm focus:ring-2 focus:ring-red-500/30 focus:border-red-400 focus:outline-none transition"
                  >
                    <option value="">Select attribute...</option>
                    {COMMON_ATTRIBUTE_KEYS.map((k) => (
                      <option key={k} value={k}>{k}</option>
                    ))}
                  </select>
                  <input
                    type="text"
                    value={attr.value}
                    onChange={(e) => updateAttr(i, 'value', e.target.value)}
                    placeholder="e.g. Red, 128GB, XL..."
                    className="flex-1 px-3 py-2 bg-white border border-gray-200 rounded-lg text-gray-900 text-sm placeholder-gray-400 focus:ring-2 focus:ring-red-500/30 focus:border-red-400 focus:outline-none transition"
                  />
                  <button
                    type="button"
                    onClick={() => removeAttr(i)}
                    className="p-2 text-gray-400 hover:text-red-600 hover:bg-red-50 rounded-lg transition-colors"
                  >
                    <X className="w-4 h-4" />
                  </button>
                </div>
              ))}
              <button
                type="button"
                onClick={addAttr}
                className="text-sm text-red-600 hover:text-red-700 flex items-center gap-1 transition-colors mt-2 font-medium"
              >
                <Plus className="w-3.5 h-3.5" /> Add attribute
              </button>
            </div>
          </div>

          <div className="grid grid-cols-2 gap-4">
            {/* Variant Code */}
            <div className="col-span-2">
              <label className="block text-sm font-medium text-gray-700 mb-1.5">
                Variant Code
                <span className="ml-2 text-xs text-gray-400 font-normal">(short code used in verification IDs, e.g. BLK, 128GB)</span>
              </label>
              <input
                name="variant_code"
                type="text"
                value={variantCode}
                onChange={(e) => setVariantCode(sanitizeCode(e.target.value))}
                placeholder="BLK"
                maxLength={8}
                className={`${inputCls} font-mono uppercase`}
              />
              {variantCode && (
                <p className="text-xs text-gray-400 mt-1 font-mono">
                  IDs will look like: <span className="text-blue-600">TRU-[MODEL]-{variantCode}-0001-K7QF</span>
                </p>
              )}
            </div>

            <div>
              <label className="block text-sm font-medium text-gray-700 mb-1.5">Price (₹) *</label>
              <input name="price" type="number" min="0" step="0.01" required placeholder="999" className={inputCls} />
              {state?.errors?.price && <p className="text-red-600 text-xs mt-1">{state.errors.price[0]}</p>}
            </div>
            <div>
              <label className="block text-sm font-medium text-gray-700 mb-1.5">Compare Price (₹)</label>
              <input name="compare_price" type="number" min="0" step="0.01" placeholder="1299" className={inputCls} />
            </div>
            <div>
              <label className="block text-sm font-medium text-gray-700 mb-1.5">Stock Quantity *</label>
              <input name="quantity" type="number" min="0" required placeholder="50" className={inputCls} />
              {state?.errors?.quantity && <p className="text-red-600 text-xs mt-1">{state.errors.quantity[0]}</p>}
            </div>
            <div>
              <label className="block text-sm font-medium text-gray-700 mb-1.5">Brand Owner SKU</label>
              <input name="seller_sku" type="text" placeholder="MY-SKU-001" className={`${inputCls} font-mono`} />
            </div>
            <div className="col-span-2">
              <label className="block text-sm font-medium text-gray-700 mb-1.5">Variant ID (optional)</label>
              <input name="variant_id" type="text" placeholder="PROD-001-V1" className={`${inputCls} font-mono`} />
            </div>
            <div className="col-span-2">
              <label className="block text-sm font-medium text-gray-700 mb-1">Variant Image URLs</label>
              <p className="text-gray-400 text-xs mb-2">Comma or newline separated. First URL becomes thumbnail.</p>
              <textarea name="image_url" rows={2} placeholder="https://cdn.example.com/red-xl.jpg" className={`${inputCls} font-mono`} />
            </div>
          </div>

          <div className="flex justify-end pt-2">
            <button type="submit" disabled={pending}
              className="flex items-center gap-2 bg-red-600 hover:bg-red-700 disabled:opacity-50 text-white px-6 py-2.5 rounded-xl font-semibold transition-colors shadow-sm text-sm">
              {pending ? <Loader2 className="w-4 h-4 animate-spin" /> : <Plus className="w-4 h-4" />}
              {pending ? 'Adding...' : 'Add Variant'}
            </button>
          </div>
        </form>
      </div>

      {/* ── Generate Verification IDs (shown after successful creation) ── */}
      {state?.success && state.variantId && (
        <div className="bg-white border border-gray-200 rounded-2xl p-6 shadow-sm">
          <h3 className="text-gray-900 font-bold text-base mb-1 flex items-center gap-2">
            Generate Verification IDs
          </h3>
          <p className="text-gray-500 text-xs mb-4">
            Create unique verification IDs for each physical unit of this variant.
            {!state.variantCode && (
              <span className="text-amber-600 ml-1">Set a Variant Code first to enable generation.</span>
            )}
          </p>

          {genError && (
            <div className="mb-4 p-3 bg-red-50 border border-red-200 rounded-xl text-red-600 text-sm">
              {genError}
            </div>
          )}

          <div className="flex items-end gap-3 mb-4">
            <div className="flex-1 max-w-[180px]">
              <label className="block text-xs font-medium text-gray-600 mb-1.5">Number of Units</label>
              <input
                type="number"
                min={1}
                max={1000}
                value={genQty}
                onChange={(e) => setGenQty(Math.min(1000, Math.max(1, parseInt(e.target.value) || 1)))}
                className="w-full px-3 py-2 bg-white border border-gray-200 rounded-xl text-gray-900 text-sm font-mono focus:outline-none focus:ring-2 focus:ring-red-500/30 focus:border-red-400 transition"
              />
            </div>
            <button
              type="button"
              onClick={handleGenerateIds}
              disabled={genLoading || !state.variantCode}
              className="flex items-center gap-2 bg-red-600 hover:bg-red-700 disabled:opacity-40 text-white px-4 py-2 rounded-xl font-semibold text-sm transition-colors shadow-sm"
            >
              {genLoading ? <Loader2 className="w-4 h-4 animate-spin" /> : null}
              {genLoading ? 'Generating...' : 'Generate IDs'}
            </button>
          </div>

          {/* Results */}
          {generatedIds.length > 0 && (
            <div>
              <div className="flex items-center justify-between mb-3">
                <span className="text-sm font-semibold text-gray-900">
                  {generatedIds.length} IDs generated
                </span>
                <div className="flex gap-2">
                  <button
                    type="button"
                    onClick={() => downloadCsv(generatedIds)}
                    className="flex items-center gap-1.5 px-3 py-1.5 rounded-lg bg-gray-100 hover:bg-gray-200 text-gray-700 text-xs font-semibold transition-colors"
                  >
                    <Download className="w-3.5 h-3.5" /> CSV
                  </button>
                  <button
                    type="button"
                    onClick={() => printIds(generatedIds)}
                    className="flex items-center gap-1.5 px-3 py-1.5 rounded-lg bg-gray-100 hover:bg-gray-200 text-gray-700 text-xs font-semibold transition-colors"
                  >
                    <Printer className="w-3.5 h-3.5" /> Print
                  </button>
                </div>
              </div>
              <div className="border border-gray-200 rounded-xl overflow-hidden max-h-64 overflow-y-auto">
                <table className="w-full text-xs">
                  <thead className="bg-gray-50 sticky top-0">
                    <tr>
                      <th className="px-4 py-2 text-left text-gray-400 font-semibold uppercase tracking-wider w-12">#</th>
                      <th className="px-4 py-2 text-left text-gray-400 font-semibold uppercase tracking-wider">Verification ID</th>
                    </tr>
                  </thead>
                  <tbody className="divide-y divide-gray-100">
                    {generatedIds.map((id, i) => (
                      <tr key={id} className="hover:bg-gray-50">
                        <td className="px-4 py-2 text-gray-400">{i + 1}</td>
                        <td className="px-4 py-2 font-mono text-gray-900 font-semibold">{id}</td>
                      </tr>
                    ))}
                  </tbody>
                </table>
              </div>
            </div>
          )}
        </div>
      )}
    </div>
  );
}
